### ISSUE TITLE
Linq and Xpath

### ISSUE THREAD

**Issue by MortalCatalyst** [multiplex/multiplex.js#15]
Hi 

I want to use multiplex as basis for data munging in js. Does multiplex cover this in total or should i be using an xpath library in conjunction with multiplex?

**Comment by KamyarNazeri** [comment]
Multiplex can iterate an object only if it follows ECMA iteration protocol, or .Net Enumerable interface. That being said, you can use either types with default iteration behavior such as Arrays, Strings, Set, Map, etc. or those implementing iterator protocol. 
We do not currently support XPath, since it does not conform to ECMA iteration protocol. However, you could easily implement iterable behavior by extending XPath result objects. So for example, if you are using  `XPathResult` on an XPath expression, you can extend it like this:

Using ES6 iterator symbol:
````javascript
XPathResult.prototype[Symbol.iterator] = function () {
    var xpathres = this;
    return {
        next: function () {
            var res = xpathres.iterateNext();
            if (res) {
                return { done: false, value: res };
            }
            return { done: true };
        }
    }
}
````

and then query your result with multiplex:
````javascript
mx(document.evaluate('//div', document, null, XPathResult.ANY_TYPE, null )).toArray()
````

Or if you prefer non ES6, .Net-like implementation:

````javascript
XPathResult.prototype.getEnumerator = function () {
    var xpathres = this;
    return {
        current: undefined,
        next: function () {
            var res = xpathres.iterateNext();
            if (res) {
                this.current = res;
                return true;
            }
            else {
                this.current = undefined;
                return false;
            }
        }
    }
}
````
